version: "3.8"
name: fl-backend
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379" # Default Redis port

  backend-service:
    build: .
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL
    volumes:
      - "./:/backend"
    depends_on:
      - redis
