name: pr-review
on:
    pull_request:
        types: [opened, synchronize]
jobs:
    review:
        name: ChatGPT code review
        runs-on: ubuntu-latest
        steps:
            - uses: agogear/chatgpt-pr-review@0.0.13
              with:
                  files: "*.tsx,*.py"
                  openai_api_key: sk-proj-THrcdhXhSWvgDU5UmZYBT3BlbkFJCiVY6h6k2djIx47iM9Uz
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  github_pr_id: ${{ github.event.number }}
